name: Build and Sign

on:
  workflow_dispatch:
    inputs:

      source_branch:
        description: 'The source branch or ref to build from'
        default: 'main'
        required: true

      release_name:
        description: 'The name for the release'
        required: true


env:
  SOURCE_REPOSITORY: 'AbdulrhmanGoni/denokv-gui-client'
  SOURCE_REPOSITORY_NAME: 'denokv-gui-client'
  NODE_NO_WARNINGS: 1
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  npm_config_fund: false
  USE_HARD_LINKS: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    environment: OSSign
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # repository: ${{ env.SOURCE_REPOSITORY }}
          repository: scheibling/denokv-gui-client-codesign
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 1

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "24.15.0"

      - name: Install dependencies
        run: npm ci

      - name: Build app's packages
        run: npm run build

      - name: Build the app
        env:
          OSSIGN_CONFIG: ${{ secrets.OSSIGN_CONFIG }}
        run: npm run compile -- --win -p never

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.msi
            dist/*.exe
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.run_id }}
          body: |
            <img src="https://github.com/ossign.png" alt="OSSign Logo" width="100" height="100" />
            # Signed Release ${{ github.event.inputs.release_name }}
            
            These are the distributable files for the signed release of ${{ env.SOURCE_REPOSITORY_NAME }} ${{ github.event.inputs.release_name }}

            The source code was fetched from https://github.com/${{ env.SOURCE_REPOSITORY }}@${{ github.event.inputs.source_branch }}
            
          

